In [1]:
#libraries
import pandas as pd
import numpy as np

In [2]:
weapon = pd.read_csv('weapon.csv')
size = pd.read_csv('size.csv')
quality = pd.read_csv('quality.csv')

In [3]:
#randon
d10 = np.random.randint(10)
d5  = np.random.randint(5)
d3  = np.random.randint(3)

In [6]:
weapon_name = str(quality.iloc[d5,0] + ' ' + size.iloc[d3,0] + ' ' + weapon.iloc[d10,0]).replace('Normal ', '').replace('Medium ', '')
price = str(size.iloc[d3,1] * quality.iloc[d5,2] * 10)
damage = size.iloc[d3,2]
hand = weapon.iloc[d10,d3+3]
bonus = quality.iloc[3,1]
range = weapon.iloc[d10,1]
damage_type = weapon.iloc[d10,2]

if bonus > 0:
    bonus_str = ('+' + str(bonus))
elif bonus < 0:
    bonus_str = str(bonus)
else:
    bonus_str = ''

print(weapon_name + '\n' + price + '\n' + hand + '\n' + damage +  bonus_str + range + damage_type )


Rudimentary Short Staff
10
1-H
d4+1meleeBludgeoning


In [44]:
if bonus > 0: bonus_str = ('+' + str(bonus))
elif bonus < 0: bonus_str = str(bonus)
else: bonus_str = ''

bonus_str

'+1'

In [20]:
import random as r
r.randint(2, 10)

7

In [40]:
#arrays
weapon_type = np.array(['Axe', 'Dagger', 'Hammer', 'Mace', 'Spear', 'Staff', 'Sword', 'Bow', 'Crossbow', 'Sling'])
weapon_type_damage = np.array(['Slashing', 'Piercing / Slashing', 'Bludgeoning', 'Bludgeoning', 'Piercing', 'Bludgeoning', 'Slashing', 'Piercing', 'Piercing', 'Bludgeoning'])
weapon_range = np.concatenate((np.repeat('Melee', 7), np.repeat('Ranged', 3)), axis=0)
weapon_size = np.array(['Short', 'Normal', 'Large'])
weapon_quality = np.array(['Rudimentary' , 'Regular', 'Notable', 'Exceptional'])
weapon_damage = np.array(['-1', '+0', '+1', '+2'])
weapon_die = np.array(['d4', 'd6', 'd8'])
weapon_price_size = np.array([1, 5, 10])
weapon_price_quality = np.array([1, 5, 25, 100])

In [55]:
matrix = np.array([
    ['1-H', '1-H', '1-H', '1-H', '1-H', '1-H', '1-H', '2-H', '2-H', '1-H'],
    ['1-H', '1-H', '1-H', '1-H', '1-H', '1-H', '1-H', '2-H', '2-H', '1-H'],
    ['2-H', '2-H', '2-H', '2-H', '2-H', '2-H', '2-H', '2-H', '2-H', '2-H']
    ])
matrix[0][0]

'1-H'

In [22]:
#randon
d10 = np.random.randint(10)
d4  = np.random.randint(4)
d3  = np.random.randint(3)

In [41]:
weapon = str(weapon_quality[d4] + ' ' + weapon_size[d3] + ' ' + weapon_type[d10]).replace('Normal ', '')
damage = str(weapon_die[d3] + weapon_damage[d4]).replace('+0', '')
price = weapon_price_quality[d4] * weapon_price_size[d3]
type_dmg = weapon_type_damage[d10]
type_dmg

'Piercing'

In [32]:
a = weapon_price_size[d3]

In [33]:
b = weapon_price_quality[d4]

In [34]:
a*b

1000

type: Regular Dagger
size: Normal
quality: Regular
range: Melee
die: d6
price: 5
weapon: Regular Normal Dagger



In [123]:
s = "Flexible"
x = "b"
y = "p"
table = s.maketrans(x, y)
print(s.translate(table))
table

Flexiple


{98: 112}

In [97]:
df = pd.DataFrame({
    weapon_type[d10],
    weapon_range[d10]
    },
    index=['type', 'range'],
    columns=['weapon']
)
df

weapon
type   Ranged
range   Sling

In [31]:
dados = {'ddd': 1}
type(aaa)

dict

In [63]:
z = pd.DataFrame(weapon_type, columns=['a'])
z.reset_index(drop=True, inplace=True)
z


a
0       Axe
1    Dagger
2    Hammer
3      Mace
4     Spear
5     Staff
6     Sword
7       Bow
8  Crossbow
9     Sling

array([8])

In [4]:
d10 = np.random.randint(10, size=1)+1
d10

array([ 4,  5,  1,  2,  7,  3,  4,  3,  4,  7,  2, 10,  6,  9,  3,  3,  6,
        8,  3,  3,  8,  4,  7,  4,  5,  1,  5,  2,  2, 10,  7, 10,  7,  6,
        8,  9, 10,  7,  9, 10,  4,  5,  2,  6,  5, 10,  6,  1,  1,  8,  7,
        7,  2,  2,  9,  3,  1,  5,  2,  2, 10,  1,  6,  3,  2, 10,  6,  1,
        8,  9,  7,  2,  5,  2,  5,  8,  2,  9,  3,  6,  7,  4,  8,  3,  4,
        9,  3,  9, 10,  4,  7,  4,  5,  8,  6,  2, 10,  4,  6,  4])

In [35]:
weapon_size = pd.DataFrame(['Short', 'Normal', 'Large'], ['d4', 'd6', 'd8'])

In [49]:
weapon_price

array([ 2,  6, 11])

In [43]:
weapon_price*2

[1, 5, 10, 1, 5, 10]

In [24]:
weapon_size = (['Short', 'Normal', 'Large'], ['d4', 'd6', 'd8'])

In [32]:
weapon_size.dtypes()

AttributeError: 'tuple' object has no attribute 'dtypes'